"""Add spotify refresh token

Revision ID: 8549a7abf2c8
Revises: df9f8c44de46
Create Date: 2025-08-07 06:17:02.870156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8549a7abf2c8'
down_revision = 'df9f8c44de46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('spotify_refresh_token')

    # ### end Alembic commands ###
