"""Clean local schema

Revision ID: df9f8c44de46
Revises: 
Create Date: 2025-08-06 09:48:18.578471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9f8c44de46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('prayer_type', sa.String(length=50), nullable=False),
    sa.Column('spiritual_focus', sa.String(length=100), nullable=True),
    sa.Column('scripture_reference', sa.String(length=100), nullable=True),
    sa.Column('church_service_date', sa.Date(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prayer')
    # ### end Alembic commands ###
