[program:unityforge]
command=/home/ubuntu/unityforge/venv/bin/gunicorn -b localhost:8000 -w 4 manage:app
directory=/home/ubuntu/unityforge
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/unityforge/gunicorn.log
stderr_logfile=/var/log/unityforge/gunicorn.err.log
environment=PATH="/home/ubuntu/unityforge/venv/bin",FLASK_ENV="production"