[program:unityforge-worker]
command=/home/ubuntu/unityforge/venv/bin/rq worker unityforge-tasks --log-level INFO
directory=/home/ubuntu/unityforge
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/unityforge/worker.log
stderr_logfile=/var/log/unityforge/worker.err.log
environment=PATH="/home/ubuntu/unityforge/venv/bin"

[program:unityforge-scheduler]
command=/home/ubuntu/unityforge/venv/bin/rq-scheduler --interval 60 --log-level INFO
directory=/home/ubuntu/unityforge
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/unityforge/scheduler.log
stderr_logfile=/var/log/unityforge/scheduler.err.log
environment=PATH="/home/ubuntu/unityforge/venv/bin",REDIS_URL="redis://localhost:6379/0"